### ISSUE TITLE
Detailed docs 404

### ISSUE THREAD

**Issue by syzer** [valhalla/demos#216]
From Readme.md
https://github.com/valhalla/demos/blob/gh-pages/docs/index.md
returns 404
What is the replacement?

**Comment by kevinkreiser** [comment]
this is just a standard blerb of text we put in every readme in every repo in our org. the demos repository is just some javascript tools for testing the api with a gui (ie leaflet map). we should probably put a bit of info about each demo but we have yet to do so. i can add a place holder...
