### ISSUE TITLE
Doesn't work with local Valhalla service

### ISSUE THREAD

**Issue by ptpt** [valhalla/demos#32]
It seems that by default the demo map connects MapZen's routing service instead of the local Valhalla server. I tried to change the `serviceUrl` in `L.Routing.Valhalla.js` to `http://localhost:8002/` but it still failed in browsers (tested in Firefox and Chrome) because of the Same Origin Policy (same hostname, but different port).

**Comment by kevinkreiser** [comment]
this was fixed  yesterday by: https://github.com/valhalla/tyr/pull/65. please git fetch; git merge origin/master in: tyr loki thor and odin to get this fix
