### ISSUE TITLE
dead link on index.md

### ISSUE THREAD

**Issue by glennon** [valhalla/demos#41]
Link on item number 2 of [index.md](https://github.com/valhalla/demos/blob/master/docs/index.md) is a dead link. It refers to this file: https://github.com/valhalla/mjolnir/blob/master/conf/valhalla.json

Perhaps you are looking for this file:
https://github.com/valhalla/conf/blob/master/valhalla.json

@rmglennon

**Comment by kevinkreiser** [comment]
Yeah this became a submodule.  Indeed that is the one
