### ISSUE TITLE
Starting valhalla server

### ISSUE THREAD

**Issue by knownasilya** [valhalla/demos#5]
Would love instructions for the routing demo

**Comment by kevinkreiser** [comment]
please have a read of: https://github.com/valhalla/demos/blob/master/docs/index.md

**Comment by dnesbitt61** [comment]
Also, we will be hosting a routing service in the near future and will have a demo that will allow hitting the service rather than bulding tiles and running a local tyr server.

**Comment by knownasilya** [comment]
Good to hear :+1: 

Where is the Valhalla data coming from? OSM (same as OSRM?)?

**Comment by dnesbitt61** [comment]
OSM. Some other open data sources are planned (GTFS transit information, elevation data, etc.).
