### ISSUE TITLE
elevation: sane sample interval

### ISSUE THREAD

**Issue by burritojustice** [valhalla/demos#86]
automatically choose a sane sampling interval, or set it to 1000m by default

**Comment by dnesbitt61** [comment]
1km is way too much! I was testing a path that is about 5K and to get a good elevation chart you need 50m or so sampling.

**Comment by burritojustice** [comment]
agreed at that zoom level! but I'd like the user to not encounter an error as they zoom out.

given this table: http://wiki.openstreetmap.org/wiki/Zoom_levels maybe we can figure out a dynamic scale based on zoom level. 

The meters per pixel calculation seems to work across zoom levels as a lower limit for sampling distance. And maybe 10x that for an upper limit? We could obviously increase the sampling distance even more at wider zoom levels (below 9), but that S=C*cos(y)/2^(z+8) equation could come in handy regardless.

**Comment by kevinkreiser** [comment]
i agree with @burritojustice  that we should set the range of the slider based on the zoom level. you could do a cool cross ocean chart to see the mariana trench if you allow for say a 3k sample distance at zl 7 or 8 or something. changing the range of the slider per zoom level does make a lot of sense to me and it would be easy to implement.
